<?xml version="1.0" encoding="UTF-8"?>
<!-- 声明内部dtd -->
<!DOCTYPE scores[
	<!ELEMENT scores (student+)>
	<!ELEMENT student (name,course,score)>
	<!ATTLIST student id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT course (#PCDATA)>
	<!ELEMENT score (#PCDATA)>
]>

<scores>
	<student id="1">
		<name>wangtong</name>
		<course>java</course>
		<score>89</score>
	</student>
	<student id="2">
		<name>wantong</name>
		<course>java</course>
		<score>89</score>
	</student>
	<student id="3">
	<name></name>
	<course></course>
	<score></score>
	</student>
	
</scores>